global:
  imagePullPolicy: Always

pulsar:
  namespace: pulsar
  namespaceCreate: true
  zookeeper:
    replicaCount: 1
    podMonitor:
      enabled: false
  broker:
    replicaCount: 1
    podMonitor:
      enabled: false
  bookkeeper:
    replicaCount: 1
    podMonitor:
      enabled: false
    persistence:
      ledgers:
        size: 2Gi
      journal:
        size: 1Gi
  autorecovery:
    podMonitor:
      enabled: false
  proxy:
    replicaCount: 1
    podMonitor:
      enabled: false
  kube-prometheus-stack:
    enabled: false
    prometheusOperator:
      enabled: false
    grafana:
      enabled: false
    alertmanager:
      enabled: false
    prometheus:
      enabled: false

postgresql:
  namespaceOverride: postgresql
  image:
    registry: docker.io
    repository: bitnami/postgresql
    digest: "sha256:4237ea262ad7aa0fdbb5f04015581cc6372aecb6741cce97ddaca3fe51ebeceb"
  auth:
    username: postgres
    password: postgres
    database: jobber
  persistence:
    size: 1Gi

jobs:
  enabled: true
  replicas: 1
  image: '655916713564.dkr.ecr.eu-north-1.amazonaws.com/jobber/jobs:latest'
  port: 3001
