{{- if .Values.jobs.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: products-grpc
  labels:
    app: products
spec:
  type: ClusterIP
  selector:
    app: products
  ports:
    - protocol: TCP
      port: {{ .Values.products.port.grpc }} 
      targetPort: {{ .Values.products.port.grpc }}
{{- end }}